version: '3'

# networks:
#     uniting_net:

services:

  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    # networks:
    #   - uniting_net
    tty: true
    stdin_open: true
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # networks:
    #   - uniting_net
    restart: always
    # container_name: postgres
