CREATE TABLE IF NOT EXISTS requests(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method varchar(10),
  uri text,
  proto varchar(10),
  body text,
  sch text
                                   );


CREATE TABLE IF NOT EXISTS headers(
  id serial primary key,
  req_id INT NOT NULL REFERENCES requests(id),
  key text,
  value text
                                  );